-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create a separate schema for CineScale
CREATE SCHEMA IF NOT EXISTS cinescale;

-- Movie metadata table
CREATE TABLE IF NOT EXISTS cinescale.movies (
    movie_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    release_year SMALLINT,
    genres TEXT
);

-- User embeddings generated by ALS
CREATE TABLE IF NOT EXISTS cinescale.user_factors (
    user_id INTEGER PRIMARY KEY,
    features VECTOR(50) NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Movie embeddings generated by ALS
CREATE TABLE IF NOT EXISTS cinescale.movie_factors (
    movie_id INTEGER PRIMARY KEY,
    features VECTOR(50) NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Historical user ratings
CREATE TABLE IF NOT EXISTS cinescale.ratings (
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    rating NUMERIC(2,1) NOT NULL,
    rated_at TIMESTAMPTZ,

    PRIMARY KEY (user_id, movie_id),

    CONSTRAINT fk_ratings_movie
        FOREIGN KEY (movie_id)
        REFERENCES cinescale.movies(movie_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_rating_range
        CHECK (rating BETWEEN 0.5 AND 5.0)
);

-- HNSW cosine similarity index
CREATE INDEX IF NOT EXISTS idx_movie_factors_hnsw_cosine
ON cinescale.movie_factors
USING hnsw (features vector_cosine_ops)
WITH (
    m = 16,
    ef_construction = 64
);

-- Helpful index for user rating history
CREATE INDEX IF NOT EXISTS idx_ratings_user_id
ON cinescale.ratings (user_id);